### PR TITLE
Make signal sent to kill process configurable

### PR DESCRIPTION
**Pull request by bjeanes**
Addresses #17 

``` ruby
Slowpoke.signal = "TERM"
```

### CODE REVIEW

**Comment by ankane** [comment]
Thanks again @bjeanes. This is pretty clean, but I don't recommend using Slowpoke with Puma. It can lead to denial of service, since the whole process gets restarted if a single thread times out.

**Comment by bjeanes** [comment]
Hmm... I'm not sure what the alternative is, really. If the timeout happens at a bad time and corrupts state (e.g. ActiveRecord's prepared statement cache, as happens often enough in my case) then that worker is screwed anyway...

**Comment by ankane** [comment]
That's fair. Instead an option, how about a `defined?(::Puma)` so it's zero config?

**Comment by bjeanes** [comment]
Is Puma the only server that uses that "TERM" in this way?

**Comment by ankane** [comment]
Not sure, but we can add more if needed.

**Comment by bjeanes** [comment]
So are you proposing keeping the API I've extended, but varying the default by known servers? Or to not extend the API and just change the Signal conditionally, a la the Phusion special case?

**Comment by ankane** [comment]
I'm proposing not extending the API

**Comment by hundredwatt** [comment]
@ankane @bjeanes We just implemented a patch for Puma today. Was about to submit this as a PR when I saw this discussion:

```
fail 'wrong slowpoke version' unless Gem::Specification.find_by_name('slowpoke').version.version == '0.1.3'

require 'slowpoke/middleware'

module Slowpoke
  class Middleware
    def call(env)
      @app.call(env)
    ensure
      if env[Slowpoke::ENV_KEY]
        # extremely important
        # protect the process with a restart
        # https://github.com/heroku/rack-timeout/issues/39
        # can't do in timed_out state consistently
        if defined?(::PhusionPassenger)
          `passenger-config detach-process #{Process.pid}`
        elsif defined?(::Puma)
          Process.kill('TERM', Process.pid)
        else
          Process.kill('QUIT', Process.pid)
        end
      end
    end
  end
end
```

**Comment by hundredwatt** [comment]
Converted that to a PR: https://github.com/ankane/slowpoke/pull/20

**Comment by bjeanes** [comment]
> I'm proposing not extending the API

Sweet looks like #20 does that nicely then! 😀

**Comment by bjeanes** [comment]
> I don't recommend using Slowpoke with Puma. It can lead to denial of service, since the whole process gets restarted if a single thread times out.

Given this, I believe it's still worth disclaiming this on the README in some fashion. In my case, I'm not too worried because we run Puma in a multi-process, multi-thread configuration, but it may have more dire impacts for others!

**Comment by ankane** [comment]
It's mentioned in the Threaded Servers section https://github.com/ankane/slowpoke#threaded-servers

**Pull request closed without merging**
