### PR TITLE
Support Rails without ActiveRecord loaded

### PR DESCRIPTION
**Pull request by joevandyk**

### CODE REVIEW

**Comment by ankane** [comment]
Hi @joevandyk, thanks for the PR! To keep the changeset minimal, I think we could accomplish this with:

```ruby
ActiveSupport.on_load(:active_record) do
  ActiveRecord::Migration.prepend(Slowpoke::Migration)
end
```

**Comment by joevandyk** [comment]
Ah, lgtm to me. Want me to make a pull with that change or will you?

**Comment by ankane** [comment]
Go for it. Would be good to make sure it works for your application.

**Comment by joevandyk** [comment]
updated the pull request, seems to work for me! thanks.

**Comment by ankane** [comment]
Cool, thanks for the contribution! 👍

**Pull request merged**
