### PR TITLE
Only inject Postgres DB timeout when necessary.

### PR DESCRIPTION
**Pull request by DouweM**
I was getting the following error since I don't use Postgres:

```
Gem::LoadError: pg is not part of the bundle. Add it to Gemfile.
```

### CODE REVIEW

**Comment by randx** [comment]
@ankane hey. Sorry for bothering you but is it any chance this can be reviewed soon? We like  `slowpoke` and want to use in our app [GitLab](https://github.com/gitlabhq/gitlabhq) but we have to support non postgresql configuration.

**Comment by ankane** [comment]
Great, thanks @DouweM!

**Comment by DouweM** [comment]
Thanks for the merge @ankane, any chance you could do a gem release? :)

**Comment by ankane** [comment]
Already done.

**Comment by DouweM** [comment]
@ankane You're the best. Thanks for making Slowpoke.

**Comment by ankane** [comment]
Np, thanks for the pull request.

**Pull request merged**
